# Generated by Django 4.0.5 on 2023-06-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tintuc',
            name='DuongDan',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
