# Generated by Django 4.0.5 on 2023-06-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_tintuc_duongdan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tintuc',
            name='DuongDan',
            field=models.SlugField(blank=True, max_length=550, null=True),
        ),
    ]
