# Generated by Django 4.0.5 on 2023-06-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_tintuc_duongdan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tintuc',
            options={'verbose_name': 'Bài Viết', 'verbose_name_plural': 'Bài Viết'},
        ),
    ]
