# Generated by Django 4.0.5 on 2023-06-21 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoDienThoai', models.TextField(blank=True, max_length=11, null=True)),
                ('DiaChi', models.TextField(blank=True, max_length=500, null=True)),
                ('GioiTinh', models.CharField(choices=[('1', '0'), ('Nam', 'Nữ')], max_length=10)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
