# Generated by Django 4.0.5 on 2023-06-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='khachhang',
            options={'verbose_name': 'Khách Hàng', 'verbose_name_plural': 'Khách Hàng'},
        ),
        migrations.AddField(
            model_name='khachhang',
            name='DuongDan',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
