# Generated by Django 4.0.5 on 2023-06-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_khachhang_options_khachhang_duongdan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachhang',
            name='GioiTinh',
            field=models.CharField(choices=[('1', 'Nam'), (0, 'Nữ')], max_length=10),
        ),
    ]
