# Generated by Django 4.0.5 on 2023-06-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_khachhang_gioitinh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachhang',
            name='DiaChi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='SoDienThoai',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
