# Generated by Django 4.0.5 on 2023-06-13 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChuyenMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenChuyenMuc', models.CharField(max_length=255)),
                ('DuongDan', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MauSac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenMauSac', models.CharField(max_length=255)),
                ('MaMauSac', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenSanPham', models.CharField(max_length=255)),
                ('GiaKhuyenMai', models.DecimalField(decimal_places=3, max_digits=10)),
                ('GiaBan', models.DecimalField(decimal_places=3, max_digits=10)),
                ('MoTaNgan', models.TextField(max_length=255)),
                ('MoTaDai', models.TextField()),
                ('The', models.CharField(max_length=255)),
                ('AnhChinh', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('AnhPhu1', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('AnhPhu2', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('AnhPhu3', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('DuongDan', models.SlugField()),
                ('TrangThai', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ChuyenMuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.chuyenmuc')),
                ('MauSac', models.ManyToManyField(blank=True, null=True, related_name='SanPham', to='product.mausac')),
            ],
        ),
    ]
