# Generated by Django 4.0.5 on 2023-06-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuyenmuc',
            name='DuongDan',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='DuongDan',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
