# Generated by Django 4.0.5 on 2023-06-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_chuyenmuc_duongdan_alter_sanpham_duongdan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='GiaBan',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='GiaKhuyenMai',
            field=models.IntegerField(),
        ),
    ]
