# Generated by Django 4.0.5 on 2023-06-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_sanpham_giaban_alter_sanpham_giakhuyenmai'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='PhanTramGiam',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
