# Generated by Django 4.0.5 on 2023-06-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_sanpham_phantramgiam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='TenSanPham',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
