# Generated by Django 4.0.5 on 2023-06-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_sanpham_tensanpham'),
    ]

    operations = [
        migrations.AddField(
            model_name='chuyenmuc',
            name='HinhAnh',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
