# Generated by Django 4.0.5 on 2023-06-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_chuyenmuc_hinhanh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chuyenmuc',
            options={'verbose_name': 'Chuyên Mục', 'verbose_name_plural': 'Chuyên Mục'},
        ),
        migrations.AlterModelOptions(
            name='mausac',
            options={'verbose_name': 'Màu Sắc', 'verbose_name_plural': 'Màu Sắc'},
        ),
        migrations.AlterModelOptions(
            name='sanpham',
            options={'verbose_name': 'Sản Phẩm', 'verbose_name_plural': 'Sản Phẩm'},
        ),
    ]
