# Generated by Django 4.0.5 on 2023-06-14 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_alter_sanpham_giaban_alter_sanpham_giakhuyenmai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TieuDe', models.CharField(max_length=255)),
                ('MoTaNgan', models.CharField(max_length=255)),
                ('MoTaDai', models.CharField(max_length=255)),
                ('HinhAnh', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('ChuyenMuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.chuyenmuc')),
            ],
        ),
    ]
