# Generated by Django 4.0.5 on 2023-06-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='HienThi',
            field=models.BooleanField(default=True),
        ),
    ]
