# Generated by Django 4.0.5 on 2023-06-14 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_sanpham_giaban_alter_sanpham_giakhuyenmai'),
        ('website', '0002_slide_hienthi'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HinhAnh', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('HienThi', models.BooleanField(default=True)),
                ('ChuyenMuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.chuyenmuc')),
            ],
        ),
        migrations.CreateModel(
            name='BannerMid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HinhAnh', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('HienThi', models.BooleanField(default=True)),
                ('ChuyenMuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.chuyenmuc')),
            ],
        ),
        migrations.CreateModel(
            name='BannerBottom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HinhAnh', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('HienThi', models.BooleanField(default=True)),
                ('ChuyenMuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.chuyenmuc')),
            ],
        ),
    ]
