# Generated by Django 4.0.5 on 2023-06-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_bannertop_bannermid_bannerbottom'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhaTaiTro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNhaTaiTro', models.CharField(max_length=255)),
                ('HinhAnh', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
