# Generated by Django 4.0.5 on 2023-06-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_nhataitro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhataitro',
            name='HinhAnh',
            field=models.ImageField(default='uploads/1.png', upload_to='uploads/'),
        ),
    ]
