# Generated by Django 4.0.5 on 2023-06-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_nhataitro_hinhanh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhataitro',
            name='HinhAnh',
            field=models.ImageField(blank=True, default='uploads/1.png', null=True, upload_to='uploads/'),
        ),
    ]
