# Generated by Django 4.0.5 on 2023-06-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_tenloai_thongtin_loaithongtin'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaithongtin',
            name='MaLoai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
