# Generated by Django 4.0.5 on 2023-06-15 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_loaithongtin_maloai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongtin',
            name='LoaiThongTin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.loaithongtin', unique=True),
        ),
    ]
