# Generated by Django 4.0.5 on 2023-06-15 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_thongtin_loaithongtin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongtin',
            name='LoaiThongTin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.loaithongtin'),
        ),
    ]
