# Generated by Django 4.0.5 on 2023-06-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_thongtin_hinhanh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongtin',
            name='GiaTri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
