# Generated by Django 4.0.5 on 2023-06-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_thongtin_giatri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nhataitro',
            options={'verbose_name': 'Nhà Tài Trợ', 'verbose_name_plural': 'Nhà Tài Trợ'},
        ),
        migrations.AlterModelOptions(
            name='thongtin',
            options={'verbose_name': 'Thông Tin', 'verbose_name_plural': 'Thông Tin'},
        ),
    ]
