# Generated by Django 4.0.5 on 2023-06-28 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_nhataitro_options_alter_thongtin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thongtin',
            options={'verbose_name': 'Cấu Hình', 'verbose_name_plural': 'Cấu Hình'},
        ),
    ]
