# Generated by Django 4.0.5 on 2023-06-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lienhe',
            options={'verbose_name': 'Liên Hệ', 'verbose_name_plural': 'Liên Hệ'},
        ),
    ]
