# Generated by Django 4.0.5 on 2023-06-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanphamgiohang',
            name='GiaBan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sanphamgiohang',
            name='MoTaNgan',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sanphamgiohang',
            name='SoLuong',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sanphamgiohang',
            name='TenSanPham',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
