# Generated by Django 4.0.5 on 2023-06-28 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_chuyenmuc_options_alter_mausac_options_and_more'),
        ('cart', '0002_alter_sanphamgiohang_giaban_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giohang',
            name='SanPhamGioHang',
        ),
        migrations.AddField(
            model_name='giohang',
            name='GiaBan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giohang',
            name='MauSac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.mausac'),
        ),
        migrations.AddField(
            model_name='giohang',
            name='MoTaNgan',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='giohang',
            name='SanPham',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.sanpham'),
        ),
        migrations.AddField(
            model_name='giohang',
            name='SoLuong',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='giohang',
            name='TenSanPham',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='SanPhamGioHang',
        ),
    ]
