# Generated by Django 4.0.5 on 2023-07-01 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0004_alter_khachhang_diachi_alter_khachhang_sodienthoai'),
        ('product', '0007_alter_chuyenmuc_options_alter_mausac_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoDienThoai', models.CharField(max_length=11)),
                ('DiaChi', models.CharField(max_length=11)),
                ('TongTien', models.IntegerField()),
                ('ThoiGian', models.DateTimeField(auto_now_add=True)),
                ('TrangThai', models.CharField(choices=[(-1, 'Khách Hàng Hủy'), (0, 'Admin Hủy'), (1, 'Chưa Xử Lý'), (2, 'Đã Xử Lý'), (3, 'Đang Chuẩn Bị Hàng'), (4, 'Đang Giao Hàng'), (5, 'Đã Giao Hàng')], max_length=25)),
                ('KhachHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.khachhang')),
            ],
            options={
                'verbose_name': 'Đơn Hàng',
                'verbose_name_plural': 'Đơn Hàng',
            },
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GiaBan', models.IntegerField()),
                ('SoLuong', models.IntegerField()),
                ('TongTien', models.IntegerField()),
                ('DonHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.donhang')),
                ('SanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sanpham')),
            ],
            options={
                'verbose_name': 'Chi Tiết Đơn Hàng',
                'verbose_name_plural': 'Chi Tiết Đơn Hàng',
            },
        ),
    ]
