# Generated by Django 4.0.5 on 2023-07-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_donhang_ghichu_alter_donhang_trangthai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietdonhang',
            name='GiaBan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chitietdonhang',
            name='SoLuong',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chitietdonhang',
            name='TongTien',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
