# Generated by Django 4.0.5 on 2023-07-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_chitietdonhang_giaban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='TrangThai',
            field=models.CharField(choices=[(1, 'Chưa Xử Lý'), (2, 'Đã Xử Lý'), (3, 'Đang Chuẩn Bị Hàng'), (4, 'Đang Giao Hàng'), (5, 'Đã Giao Hàng'), (6, 'Khách Hàng Hủy'), (7, 'Admin Hủy')], default=1, max_length=25),
        ),
    ]
