# Generated by Django 4.2.4 on 2023-09-07 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_sanpham_motadai'),
        ('order', '0007_alter_donhang_trangthai'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietdonhang',
            name='MauSac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.mausac'),
        ),
    ]
